services:
  - type: web
    name: project-management-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: project-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: project-db
    databaseName: project_management
    user: project_user
